### ISSUE TITLE
CMake v.s. makefile

### ISSUE THREAD

**Issue by victor-yacovlev** [BaydinAlexey/proglangs_baydin#1]
1. Файл должен быть с именем `CMakeLists.txt`
2. Если использовать `make -f makefile`, то вполне естественно возникает ошибка:

```
gcc -shared -fpic floyd.cpp -o floyd.so -I/usr/include/python3.4m -L/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu -lpython3.4 -lstdc++
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lpython3.4
collect2: error: ld returned 1 exit status
makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by BaydinAlexey** [comment]
Добрый день. Смогу поправить только вечером.
Как переименую - отпишусь.
С уважением, Алексей Байдин.

2015-12-14 15:41 GMT+03:00 Victor Yacovlev notifications@github.com:
